const ADD_COUNTRY_STARTED = 'ADD_COUNTRY_STARTED'
const ADD_COUNTRY_SUCCESS = 'ADD_COUNTRY_SUCCESS'
const ADD_COUNTRY_REJECTED = 'ADD_COUNTRY_REJECTED'
export { ADD_COUNTRY_STARTED, ADD_COUNTRY_SUCCESS, ADD_COUNTRY_REJECTED }